<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\OAuthAuthorizationMiddleware::class => App\OAuthAuthorizationMiddlewareFactory::class,
            App\OauthAuthorizationMiddleware::class => App\OauthAuthorizationMiddlewareFactory::class,
            App\OauthConsentHandler::class => App\OauthConsentHandlerFactory::class,
            App\Login\LoginHandler::class => App\Login\LoginHandlerFactory::class,
            App\Login\CustomAuthenticationAdapter::class => App\Login\CustomAuthenticationAdapterFactory::class,
            App\Repository\AdapterClientRepository::class => App\Repository\AdapterClientRepositoryFactory::class,
            App\Repository\CustomUserRepository::class => App\Repository\CustomUserRepositoryFactory::class,
        ],
    ],
];
